[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
regex = "1.10.2" # Regex
#ansi_term = "0.12.1" # For color printing
clap = { version =  "4.4.12", features = ["derive"] } # Command Line Argument Parsing
tera = "1.19.1" # Temlate stuff
ureq = "2.9.1" # Web stuff
